### ISSUE TITLE
0.20.0 release with BREAKING CHANGES (yet again)

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/prettierx#550]
Motivation is to rebase the prettierX changes based on Prettier 2.3.x, as discussed in:

- PR #549
- issue #548 - support `TSNamedTupleMember` AST type from the `babel-ts` parser
- issue #414 - merge updates from Prettier 2.3.0

POSSIBLE BREAKING CHANGES:

`--space-in-parens` (originally `--paren-spacing`, as introduced in PR #16) may be removed along with some related options on a temporary basis to help speed this up:

- `--array-bracket-spacing`
- `--css-paren-spacing`
- `--computed-property-spacing option`
- `--space-unary-ops`
- `--template-curly-spacing`
- `--type-angle-bracket-spacing`
- `--type-bracket-spacing`

As before, I would like to request that people raise any objections ASAP.

/cc @jsnajdr @aMarCruz @adalinesimonian

**Comment by adalinesimonian** [comment]
When working on #549 over the weekend, I spent many hours going through every conflict, finding where the new code lived while digging through upstream commit history, merged PRs, and git blame output, then manually moving the appropriate prettierx functionality into its new home after the upstream refactors, changing it when appropriate to match new internal lint rules and API changes.

One thing that came up as I was working on the merge was that all the logic for parentheses spacing was distributed across many different files in `language-js/print/`. I was able to distribute the prettierx `--space-in-parens` support code throughout its appropriate locations. But it seems that not only has the code moved to different locations, but in some cases, the functionality has changed in non-obvious ways.

Here's one concrete example, from `needs-parens.js`. The old code:

```js
    case "NGPipeExpression":
      if (
        parent.type === "NGRoot" ||
        parent.type === "NGMicrosyntaxExpression" ||
        parent.type === "ObjectProperty" ||
        parent.type === "ArrayExpression" ||
        ((parent.type === "CallExpression" ||
          parent.type === "OptionalCallExpression") &&
          parent.arguments[name] === node) ||
        (parent.type === "NGPipeExpression" && name === "right") ||
        (parent.type === "MemberExpression" && name === "property") ||
        parent.type === "AssignmentExpression" ||
        // [prettierx] parenSpace option support (...)
        // Pipe expression already got the parens when breaking inside certain parents
        parent.type === "UnaryExpression" ||
        ((parent.type === "MemberExpression" ||
          parent.type === "OptionalMemberExpression") &&
          !parent.computed) ||
        (parent.type === "CallExpression" &&
          name === "callee" &&
          parent.callee === node)
      ) {
        return false;
      }
      return true;
```

New code, with edits to conform to lint rules:

```js
    case "NGPipeExpression":
      if (
        parent.type === "NGRoot" ||
        parent.type === "NGMicrosyntaxExpression" ||
        (parent.type === "ObjectProperty" &&
          // Preserve parens for compatibility with AngularJS expressions
          !(node.extra && node.extra.parenthesized)) ||
        parent.type === "ArrayExpression" ||
        (isCallExpression(parent) && parent.arguments[name] === node) ||
        (name === "right" && parent.type === "NGPipeExpression") ||
        (name === "property" && parent.type === "MemberExpression") ||
        parent.type === "AssignmentExpression" ||
        // [prettierx] parenSpace option support (...)
        // Pipe expression already got the parens when breaking inside certain parents
        parent.type === "UnaryExpression" ||
        ((parent.type === "MemberExpression" ||
          parent.type === "OptionalMemberExpression") &&
          !parent.computed) ||
        (name === "callee" &&
          parent.type === "CallExpression")
      ) {
        return false;
      }
      return true;
```

However, even though on the surface it seems as though everything's fine, it turns out that the assumption that parentheses are already in place isn't true anymore, as this failing test shows:

```
expect(received).toMatchSnapshot()

    Snapshot name: `attributes.component.html - {"printWidth":1} format 1`

    - Snapshot  - 6
    + Received  + 6

    @@ -434,28 +434,28 @@
            ?.errors
            .min
        "
        [ngClass]="{
          'btn-success':
    -       (
    +
              dialog$
              | async
    -       )
    +
              .level ===
            dialogLevelEnum.SUCCESS,
          'btn-warning':
    -       (
    +
              dialog$
              | async
    -       )
    +
              .level ===
            dialogLevelEnum.WARNING,
          'btn-svg':
    -       (
    +
              dialog$
              | async
    -       )
    +
              .level ===
            dialogLevelEnum.DANGER
        }"
        [stickout]="
          +toolAssembly.stickoutMm

      279 |         CURSOR_PLACEHOLDER,
      280 |       })
    > 281 |     ).toMatchSnapshot();
          |       ^
      282 |   });
      283 |
      284 |   if (!FULL_TEST) {

      at Object.<anonymous> (tests/config/format-test.js:281:7)
```

Maybe the fix involves checking `node.extra.parenthesized`, an example of which is in this new code. But that takes a little bit of digging to make sure it's doing what we expect, and this is just one test.

On the one hand, you could argue that temporarily removing support for `--space-in-parens` significantly reduces complexity because we avoid the hassle of chasing every difference in behaviour to try and patch any bugs resulting from the merge or rebase. And maybe we could apply this to any option which has a lot of friction in the differences between prettier 2.3.0 and the prettierx dev branch.

But on the other hand, perhaps another route of action could be editing option support so that prettier's options are propagated to their corresponding prettierx options, only if those options haven't been set themselves. Then, whatever actual bugs remain are commented out with a TODO, and we take a crack at them.

What I mean by that last part is maybe better explained better with a concrete example. Many tests fail in my branch because they expect prettier configuration options, some of which have been superseded by prettierx options. For example, bracket spacing is broken out into individual options, template literals and objects, etc., and it looks like they have different defaults, at least from my cursory look (I'm new to this project). We could set the individual broken-out options to whatever the general bracket spacing option is set to get those working. Then, at least in theory, all the prettier tests built around prettier's configuration options pass, though this changes functionality so that those options are base configuration options. I guess that'd be a breaking change, technically.

Then, if this really does iron out the vast majority of issues, for cases like this bug in Angular conditional behaviour, we'd comment those out with a TODO. Then, afterwards, we'd revisit those spots and restore prettierx's behaviour, correctly implemented.

It's unlikely that we'll avoid bugs entirely since there are many significant changes, but I think it depends on whether or not there are a lot of these "true" bugs or not. I think it'd be pretty simple to evaluate this by taking a closer look at exactly what's failing in the merge branch after making the change to propagate prettier options to their respective prettierx options - I think that'd be pretty straightforward to do.

So, all in all, at this point, I'm not entirely married to any specific approach to reducing friction in pulling in these upstream changes. But I think we can gather some facts to help us make a good decision pretty easily and quickly with a little poking. I might do that real quick in a separate branch by making those option changes to see how many real bugs we've got on our hands due to this merge. If there are too many of them, then I think that would back up temporarily removing option support as a more frictionless course of action. Your thoughts?

**Comment by adalinesimonian** [comment]
An update: Locally, I implemented option propagation using an `inherits` key on option definitions. Here's an example:

```js
  importCurlySpacing: {
    category: CATEGORY_JAVASCRIPT,
    type: "boolean",
    default: true,
    // causes this option to inherit the value of bracketSpacing if
    // bracketSpacing is set but importCurlySpacing isn't
    inherit: "bracketSpacing", 
    description: "Put spaces between import curly braces.",
    oppositeDescription: "Disable spaces between import curly braces.",
  },
```

 Propagating `bracketSpacing` to its corresponding broken-out replacements in prettierx got more than half of the failing test suites to pass without errors. I knocked out another half by patching a bug in import/export brace spacing. Failing test suites dropped from a whopping over 300 to a manageable 51. All this without having to add a bunch of friction between upstream and prettierx by forcing tests to be rewritten and/or increasing surface area of changes leading to more conflicts. And, of course, the added benefit of making prettierx a drop-in replacement by respecting prettier options without having to give up prettierx's granular control of settings or configurability.

I'm continuing to locate bugs and fix behaviour, so far progress has been pretty productive seeing as I only started chipping away at this just 3 days ago.

**Comment by brody2consult** [comment]
I am just curious if @adalinesimonian or anyone else has been using `--space-in-parens` or any related options. I originally introduced it in PR #16 in case it could help support the needs of WordPress, but it looks to me like they may be just using their own fork. The one issue I saw when renaming this option was that `eslint-plugin-prettierx` tries to set all options and is sensitive to this kind of renaming.

My first choice would be to keep these options for the sake of maximum flexibility, but the number of changes needed seems to compound the maintenance burden.

**Comment by brody2consult** [comment]
I do not expect to make the breaking changes discussed here in the near future, closing.
